### ISSUE TITLE
Add vCenter User 

### ISSUE THREAD

**Issue by MeinhartEsrohr** [TheSleepyAdmin/Scripts#1]
Hello TheSleepyAdmins,
I have a question, is there a possibility to define a username and password when running the script ? 
When I run the script, after a short time a window opens where I have to enter the credentials of the vCenter, so unfortunately my planned task does not work either. 
We have three vCenter servers, on one it runs without problems, on the other two the login window pops up. 

In Windows where I run the script I am logged in with my domain user who also has access to the vCenter servers.

Thank You!

**Comment by DonRWettr** [comment]
Hey there,

I've tried myself on the issue for a bit, and maybe it works by just passing along your credentials after saving them where you're running the script from:

```
$CredentialPath = $PSScriptRoot + "\Credentials\" + $env:USERNAME.clixml

if (Test-Path $PSScriptRoot\Credentials == False) {
    Write-Warning "Credentials folder does not exist, creating one..."
    New-Item -Path . -Name "Credentials" -ItemType "directory"
}

if (Test-Path -Path $CredentialPath == False) {
    Write-Warning "Credentials of current user not saved yet, prompting cmdlet..."
    Get-Credential | Export-Clixml -Path $CredentialPath
}

$Credentials = Import-clixml -Path $CredentialPath
Write-Host "Credentials of current user imported"
```

And then of course update the connect command accordingly:

`$VCStatus = connect-VIServer $VCServer -Credential $Credentials -ErrorAction SilentlyContinue -ErrorVariable ErrorProcess;`

You'll need to enter your credentials the first time you run it, but after that it should run on its own.
Again, can't verify if it works or not, since I don't have access to our vCenters right now, but maybe give it a go and see how it goes.

**Comment by TheSleepyAdmin** [comment]
Hi MeinhartEsrohr  

Sorry didn't see this issue notification. 

I have the script running against two different vCenter in linked mode and never seen the popup.  I have seen the popup issue before when the certificate from vCenter is not trusted. Have you check this. 

Also you could look at using New-VICredentialStoreItem to save credenital that can be a called later but it not something I can't add to the script as it different for each environment. 

New-VICredentialStoreItem -User domain\username -Password Password -Host vc.domain.local -File C:\Temp\vicreds.xml

$logon = Get-ViCredentialStoreItem -File C:\Temp\vicreds.xml
Connect-VIServer -Server $logon.Host -User $logon.User -Password $logon.Password
